import { Readable } from 'stream';

/**
 * Configuration options for the Supabase Storage provider
 */
export interface ProviderConfig {
  /**
   * Supabase project URL (e.g., https://xxx.supabase.co)
   */
  apiUrl: string;

  /**
   * Supabase service_role key for authentication
   */
  apiKey: string;

  /**
   * Name of the Supabase storage bucket
   */
  bucket: string;

  /**
   * Optional subdirectory within the bucket for file storage
   * @default ''
   */
  directory?: string;

  /**
   * Whether the bucket is configured as public (true) or private (false)
   * Public buckets return permanent URLs, private buckets use signed URLs
   * @default true
   */
  publicFiles?: boolean;

  /**
   * Expiration time in seconds for signed URLs (only applies to private buckets)
   * @default 3600
   */
  signedUrlExpires?: number;
}

/**
 * Strapi file object containing metadata and content
 */
export interface StrapiFile {
  /**
   * Original file name
   */
  name: string;

  /**
   * Unique hash generated by Strapi
   */
  hash: string;

  /**
   * File extension including the dot (e.g., '.jpg')
   */
  ext: string;

  /**
   * MIME type of the file
   */
  mime: string;

  /**
   * File size in kilobytes
   */
  size: number;

  /**
   * URL or path to the file (public URL for public buckets, path for private buckets)
   */
  url: string;

  /**
   * Optional file path
   */
  path?: string;

  /**
   * File content as a Buffer
   */
  buffer?: Buffer;

  /**
   * File content as a readable stream
   */
  stream?: Readable;
}

/**
 * Upload provider interface that must be implemented for Strapi v5
 */
export interface UploadProvider {
  /**
   * Upload a file to Supabase Storage
   * @param file - The file object to upload
   * @returns Promise that resolves when upload is complete
   */
  upload(file: StrapiFile): Promise<void>;

  /**
   * Upload a file stream to Supabase Storage
   * @param file - The file object with stream to upload
   * @returns Promise that resolves when upload is complete
   */
  uploadStream(file: StrapiFile): Promise<void>;

  /**
   * Delete a file from Supabase Storage
   * @param file - The file object to delete
   * @returns Promise that resolves when deletion is complete
   */
  delete(file: StrapiFile): Promise<void>;

  /**
   * Validate file size against configured limits
   * @param file - The file object to check
   * @param options - Options containing the size limit
   * @returns Promise that resolves if size is valid, rejects if exceeded
   */
  checkFileSize(file: StrapiFile, options: { sizeLimit: number }): Promise<void>;

  /**
   * Check if the bucket is configured as private
   * @returns true if bucket is private, false if public
   */
  isPrivate(): boolean;

  /**
   * Generate a signed URL for accessing a file (or return public URL for public buckets)
   * @param file - The file object to generate URL for
   * @returns Promise that resolves with an object containing the URL
   */
  getSignedUrl(file: StrapiFile): Promise<{ url: string }>;
}
